<Calculus>:
    ImageButton:
        size_hint: 0.15,0.15
        pos_hint: {"x":0,"top":1}
        source: "imgs/backBTN.png"
        on_press:
            root.manager.transition.direction = 'left'
            root.manager.transition.duration = 0
            root.manager.current = 'math_screen'
    Button:
        text: "Limits"
        bold: True
        italic: True
        size_hint: .3,.05
        pos_hint: {"x":0.7,"top":0.05}
        on_press:
            root.manager.transition.direction = 'right'
            root.manager.transition.duration = 0
            root.manager.current = 'limits_screen'
    Button:
        text: "Derivatives"
        bold: True
        italic: True
        size_hint: .3,.05
        pos_hint: {"x":0.7,"top":0.1}
        on_press:
            root.manager.transition.direction = 'right'
            root.manager.transition.duration = 0
            root.manager.current = 'derivatives_screen'