<ElectronConfigurations>:

    data: data
    result: result

    MDTextField:
        id: data
        hint_text: 'Element symbol or name, shorthand=true'
        size_hint: 0.4,0.1
        pos_hint: {'center_x':0.5,'center_y':0.8}
        font_name: 'arial-unicode-ms'
    MDRectangleFlatButton:
        text: 'Configure'
        size_hint: 0.2,0.05
        pos_hint: {'center_x':0.635,'center_y':0.7}
        on_press: root.configure()
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.365,"center_y":0.7}
        on_release: app.show_MDDialog_2('Enter the element and get back its electron configuration')
    Label:
        id: result
        text: ''
        font_size: 40
        font_name: 'arial-unicode-ms'