<Factor>:

    data: data
    result: result

    MDTextField:
        id: data
        hint_text: 'Expression'
        size_hint: 0.3,0.1
        pos_hint: {'center_x':0.5,'center_y':0.8}
        font_name: 'arial-unicode-ms'
    MDRectangleFlatButton:
        text: 'Factor'
        size_hint: 0.2,0.05
        pos_hint: {'center_x':0.635,'center_y':0.7}
        on_press: root.factorize()
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.365,"center_y":0.7}
        on_release: app.show_MDDialog_3('Currently, imaginary factorization is not supported. It will be supported in future updates.')
    Label:
        id: result
        text: ''
        font_size: 50
        font_name: 'arial-unicode-ms'