<IdealGasLaw>:

    data: data
    volume_units: volume_units
    temp_units: temp_units
    pressure_units: pressure_units
    result: result

    MDTextField:
        id: data
        hint_text: 'solve_for=R,pressure=100,temperature=25,moles=2.75,volume=1.625'
        size_hint: 0.5,1
        pos_hint: {'center_x':0.5,'center_y':0.35}
        font_name: 'arial-unicode-ms'
    MDRaisedButton:
        id: volume_units
        text: 'Volume Units'
        pos_hint: {'center_x':0.3,'center_y':0.7}
        on_release: root.change_item_a()
    MDRaisedButton:
        id: temp_units
        text: 'Temperature Units'
        pos_hint: {'center_x':0.5,'center_y':0.7}
        on_release: root.change_item_b()
    MDRaisedButton:
        id: pressure_units
        text: 'Pressure Units'
        pos_hint: {'center_x':0.7,'center_y':0.7}
        on_release: root.change_item_c()
    MDRectangleFlatButton:
        text: 'Calculate'
        size_hint: 0.2,0.05
        pos_hint: {'center_x':0.635,'center_y':0.6}
        on_release: root.ideal_gas()
    MDRectangleFlatButton:
        id: info
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {'center_x':0.365,'center_y':0.6}
        on_release: app.show_MDDialog_4('PV=nRT or PV=m/mm*RT\n\nPossible Entries: solve_for, volume, moles, temperature, pressure, mass, molar_mass, substance\n\nEx: solve_for=T,volume=3.5,moles=2,pressure=100\n\nEnter units through buttons')
    Label:
        id: result
        text: ''
        font_size: 50
        font_name: 'arial-unicode-ms'
    Label:
        text: 'PV=nRT'
        pos_hint: {'center_x':0.5,'center_y':0.4}
        font_size: 65
        font_name: 'arial-unicode-ms'