<Limits>:

    expression: expression
    variable: variable
    approaches: approaches
    result: result

    MDTextField:
        id: expression
        hint_text: 'Expression'
        size_hint: 0.3,0.1
        pos_hint: {"center_x":0.5,"center_y":0.6}
        font_name: 'arial-unicode-ms'
    MDTextField:
        id: variable
        hint_text: 'Variable'
        size_hint: 0.3,0.1
        pos_hint: {"center_x":0.5,"center_y":0.5}
        font_name: 'arial-unicode-ms'
    MDTextField:
        id: approaches
        hint_text: 'Approaches...'
        size_hint: 0.3,0.1
        pos_hint: {"center_x":0.5,"center_y":0.4}
        font_name: 'arial-unicode-ms'
    MDRectangleFlatButton:
        text: "Find the Limit"
        size_hint: .25,.05
        pos_hint: {"center_x":0.635,"center_y":0.3}
        on_press: root.findTheLimit()
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.365,"center_y":0.3}
        on_release: app.show_MDDialog_5('Enter the expression, variable, and value the variable is approaching')
    Label:
        id: result
        text: ""
        bold: True
        font_size: 50
        font_name: 'arial-unicode-ms'
