<Molarity>:

    data: data
    result: result

    MDTextField:
        id: data
        hint_text: 'volume=17.8mL, mass=18.9g, chemical=H₂O'
        size_hint: 0.45,0.1
        pos_hint: {"center_x":0.5,"center_y":0.8}
        font_name: 'arial-unicode-ms'
    MDRectangleFlatButton:
        text: 'Calculate'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.635,"center_y":0.7}
        on_press: root.calc()
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.365,"center_y":0.7}
        on_release: app.show_MDDialog_7('Possible entries: volume (mL/L), mass, chemical, moles. Enter as a comma-separated list.')
    Label:
        id: result
        text: ''
        bold: True
        font_size: 75
        font_name: 'arial-unicode-ms'