<OxidationNumbers>:

    data: data
    result: result

    MDTextField:
        id: data
        hint_text: 'Compound'
        size_hint: 0.25,0.1
        pos_hint: {'center_x':0.5,'center_y':0.8}
        font_name: 'arial-unicode-ms'
    MDRectangleFlatButton:
        text: 'Submit'
        size_hint: 0.2,0.05
        pos_hint: {'center_x':0.635,'center_y':0.7}
        on_press: root.oxidate(None, True)
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.365,"center_y":0.7}
        on_release: app.show_MDDialog_10("Enter the compound and get each element's oxidation number")
    Label:
        id: result
        text: ''
        font_size: 50
        font_name: 'arial-unicode-ms'