<RightTriangleTrig>:

    data: data
    result: result

    MDTextField:
        id: data
        hint_text: 'c=1, A=90°, B=π/3'
        size_hint: 0.3,0.1
        pos_hint: {"center_x":0.8,"center_y":0.8}
        font_name: 'arial-unicode-ms'
    MDRectangleFlatButton:
        text: 'Solve'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.8,"center_y":0.675}
        on_press: root.solve()
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.8,"center_y":0.575}
        on_release: app.show_MDDialog_12('A,B,C are the angle values; a,b,c are the side lengths. All angles are in RADIANS.')
    Label:
        id: result
        text: ''
        bold: True
        font_size: 35
        pos_hint: {'center_x':0.2,'center_y':0.75}
        font_name: 'arial-unicode-ms'