<Stoichiometry>:
    id: stoich

    equation: equation
    amount: amount
    start: start
    end: end
    start_unit: start_unit
    end_unit: end_unit
    result: result

    MDTextField:
        id: equation
        hint_text: 'Equation'
        size_hint: 0.35,0.1
        pos_hint: {'center_x':0.5,'center_y':0.83}
        font_name: 'arial-unicode-ms'
    MDTextField:
        id: amount
        hint_text: 'Starting Amount'
        size_hint: 0.35,0.1
        pos_hint: {'center_x':0.5,'center_y':0.53}
        font_name: 'arial-unicode-ms'
    MDTextField:
        id: start
        hint_text: 'Starting Compound'
        size_hint: 0.35,0.1
        pos_hint: {'center_x':0.5,'center_y':0.73}
        font_name: 'arial-unicode-ms'
    MDTextField:
        id: end
        hint_text: 'Ending Compound'
        size_hint: 0.35,0.1
        pos_hint: {'center_x':0.5,'center_y':0.63}
        font_name: 'arial-unicode-ms'
    MDRaisedButton:
        id: start_unit
        text: 'Start Units'
        pos_hint: {'center_x':0.4,'center_y':0.43}
        on_release: root.change_item_a()
    MDRaisedButton:
        id: end_unit
        text: 'End Units'
        pos_hint: {'center_x':0.6,'center_y':0.43}
        on_release: root.change_item_b()
    MDRectangleFlatButton:
        text: 'Calculate'
        size_hint: 0.2,0.05
        pos_hint: {'center_x': 0.635, 'center_y': 0.3}
        on_press: root.read()
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.365,"center_y":0.3}
        on_release: app.show_MDDialog_14('Currently, solution stoichiometry is not supported. It will be supported in future updates.')
    Label:
        id: result
        text: ''
        bold: True
        pos_hint: {'center_x': 0.5, 'center_y': 0.2}
        font_name: 'arial-unicode-ms'
        font_size: 50






