<UnitCircle>:

    data: data
    result: result

    MDTextField:
        id: data
        hint_text: 'func=sin, angle=90°'
        size_hint: 0.3,0.1
        pos_hint: {"center_x":0.8,"center_y":0.8}
    MDRectangleFlatButton:
        text: "Evaluate"
        size_hint: .2,.05
        pos_hint: {"center_x":0.8,"center_y":0.7}
        on_press: root.evaulateTrig()
    MDRectangleFlatButton:
        text: 'Info'
        size_hint: 0.2,0.05
        pos_hint: {"center_x":0.8,"center_y":0.6}
        on_release: app.show_MDDialog_15('Enter the trigonometric function and angle and get back the value')
    Label:
        id: result
        text: ""
        font_size: 65
        pos_hint: {"center_x":0.5, "center_y":0.2}
